// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtpeigiowvfnbpvxzdhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cGVpZ2lvd3ZmbmJwdnh6ZGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjIzNDksImV4cCI6MjA3MDIzODM0OX0.t07A5jDvkXfEUDC5Wv8jKJ6dxSLMltoIQ6TnT9ckmuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});