// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yakafnzqsijlipwerboo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlha2Fmbnpxc2lqbGlwd2VyYm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTE5NTIsImV4cCI6MjA2ODY4Nzk1Mn0.J7Pg8HzW992UFVedLIviLaQ9jiOQHZMEWWrvMrsirNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});